spring:
  security:
    oauth2:
      client:
        registration:
          aad:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid+profile+email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          aad:
            issuer-uri: ${ISSUER_URI}